# Default Spring Profile
server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.mylibrary: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
#For test
spring:
  config:
    activate:
      on-profile: test

app:
  books-service:
    host: books-service
    port: 7001
  members-service:
    host: members-service
    port: 7002
  reservations-service:
    host: reservations-service
    port: 7003
  loans-service:
    host: loans-service
    port: 7004
---

# for docker

spring:
  config:
    activate:
      on-profile: docker

server.port: 8080

#spring.datasource.hikari.initializationFailTimeout: 60000

app:
  books-service:
    host: books-service
    port: 8080
  members-service:
    host: members-service
    port: 8080
  reservations-service:
    host: reservations-service
    port: 8080
  loans-service:
    host: loans-service
    port: 8080